# Generated by Django 6.0.5 on 2026-05-11 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_id', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.department')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='universities.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('student_type', models.CharField(choices=[('local', 'Local'), ('international', 'International'), ('exchange', 'Exchange')], default='local', max_length=20)),
                ('mode_of_study', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('distance', 'Distance Learning'), ('online', 'Online')], default='full_time', max_length=20)),
                ('semester_in_programme', models.IntegerField(default=1)),
                ('tuition_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='UGX', max_length=5)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deferred', 'Deferred'), ('graduated', 'Graduated'), ('expelled', 'Expelled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('sponsorship', models.CharField(blank=True, max_length=100)),
                ('scholarship_percentage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.department')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.programme')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='universities.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('university', 'student_id')},
            },
        ),
    ]
