# Generated by Django 6.0.5 on 2026-05-11 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=3)),
                ('semester_in_programme', models.IntegerField(default=1)),
                ('max_enrollment', models.IntegerField(default=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_elective', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='students.lecturer')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.university')),
            ],
            options={
                'unique_together': {('university', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='ExamDocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_in_programme', models.IntegerField(default=1)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='generated', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_dockets', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_in_programme', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='enrolled', max_length=20)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('attendance_percentage', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ModuleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_in_programme', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped')], default='pending', max_length=20)),
                ('date_selected', models.DateTimeField(auto_now_add=True)),
                ('date_enrolled', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_selections', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'academic_year')},
            },
        ),
    ]
