# Generated by Django 6.0.5 on 2026-05-11 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('head', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('primary_color', models.CharField(default='#0D1B5E', max_length=7)),
                ('secondary_color', models.CharField(default='#C9A84C', max_length=7)),
                ('country', models.CharField(default='Uganda', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UGX', 'UGX'), ('KES', 'KES'), ('TZS', 'TZS'), ('GHS', 'GHS'), ('NGN', 'NGN'), ('ZAR', 'ZAR'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='UGX', max_length=5)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('enrollment_threshold', models.IntegerField(default=30, help_text='% to enroll')),
                ('cat1_threshold', models.IntegerField(default=50, help_text='% for CAT 1')),
                ('cat2_threshold', models.IntegerField(default=75, help_text='% for CAT 2')),
                ('exam_threshold', models.IntegerField(default=100, help_text='% for exams')),
                ('grading_scale', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('subscription_plan', models.CharField(default='trial', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='bachelor', max_length=20)),
                ('duration_years', models.IntegerField(default=3)),
                ('total_semesters', models.IntegerField(default=6)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.department')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='universities.university')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='universities.university'),
        ),
    ]
